import { TrustReport } from "../trust-report";

export function renderGitHubComment(report: TrustReport): string {
  const riskEmoji = (risk: string) =>
    risk === "critical"
      ? "🔴"
      : risk === "high"
        ? "🟠"
        : risk === "medium"
          ? "🟡"
          : "🟢";

  const lines: string[] = [
    "## Optinum — AI Blind Spot Report",
    "",
    `**Changed paths:** ${report.changedPathsCount} | **Uncovered:** ${report.uncoveredPathsCount}/${report.changedPathsCount}`,
    "",
  ];

  if (report.blindSpotsDetected.length > 0) {
    lines.push("<details>");
    lines.push(
      `<summary><strong>🔍 ${report.blindSpotsDetected.length} blind spot patterns detected</strong></summary>`,
      "",
    );
    lines.push("| Pattern | Change Type | Risk | Tests Cover This |");
    lines.push("|---------|-------------|------|-----------------|");

    for (const spot of report.blindSpotsDetected) {
      const covered = spot.testedBy.length > 0 ? "✅ Yes" : "❌ No";
      lines.push(
        `| ${spot.pattern} | ${spot.changeType} | ${riskEmoji(spot.risk)} ${spot.risk} | ${covered} |`,
      );
    }
    lines.push("</details>", "");
  }

  if (report.uncoveredPathsCount > 0) {
    lines.push(
      `> ⚠️ **${report.uncoveredPathsCount} of ${report.changedPathsCount} changed paths have zero test coverage**`,
    );
    lines.push("");
  }

  if (report.synthesizedTestsCount > 0) {
    lines.push(
      `**${report.synthesizedTestsCount} tests synthesized** — run \`npx optinum test\` to generate them`,
    );
  } else {
    lines.push(
      "_Gap analysis available. Add `OPTINUM_API_KEY` to synthesize tests._",
    );
  }

  lines.push(
    "",
    `---`,
    `_Generated by [Optinum](https://github.com/optinum/optinum) v${report.version}_`,
  );

  return lines.join("\n");
}
