import { TrustReport } from "../trust-report";

export function renderHtml(report: TrustReport): string {
  const riskColor = (risk: string) =>
    risk === "critical"
      ? "#ef4444"
      : risk === "high"
        ? "#f97316"
        : risk === "medium"
          ? "#eab308"
          : "#22c55e";

  const spotRows = report.blindSpotsDetected
    .map(
      (spot) => `
    <tr>
      <td>${escapeHtml(spot.pattern)}</td>
      <td>${escapeHtml(spot.changeType)}</td>
      <td style="color: ${riskColor(spot.risk)}">${spot.risk}</td>
      <td>${spot.testedBy.length > 0 ? "✅" : "❌"}</td>
    </tr>`,
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Optinum Trust Report</title>
  <style>
    body { font-family: -apple-system, system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
    h1 { color: #1f2937; }
    .summary { background: #f3f4f6; padding: 1rem; border-radius: 0.5rem; margin: 1rem 0; }
    table { border-collapse: collapse; width: 100%; margin-top: 1rem; }
    th, td { padding: 0.5rem 1rem; text-align: left; border-bottom: 1px solid #e5e7eb; }
    th { background: #f9fafb; font-weight: 600; }
  </style>
</head>
<body>
  <h1>🔍 Optinum — AI Blind Spot Report</h1>
  <div class="summary">
    <strong>Changed paths:</strong> ${report.changedPathsCount} &nbsp;|&nbsp;
    <strong>Uncovered:</strong> ${report.uncoveredPathsCount}/${report.changedPathsCount} &nbsp;|&nbsp;
    <strong>Blind spots:</strong> ${report.blindSpotsDetected.length}
  </div>
  ${
    report.blindSpotsDetected.length > 0
      ? `
  <h2>Blind Spots Detected</h2>
  <table>
    <thead><tr><th>Pattern</th><th>Change Type</th><th>Risk</th><th>Tests Cover</th></tr></thead>
    <tbody>${spotRows}</tbody>
  </table>`
      : "<p>No blind spot patterns detected.</p>"
  }
  <footer style="margin-top: 2rem; color: #6b7280; font-size: 0.875rem;">
    Generated by Optinum v${escapeHtml(report.version)}
  </footer>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
